# Generated by Django 5.0.6 on 2024-06-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StudentName',
            new_name='studentName',
        ),
    ]
