# Generated by Django 5.0.6 on 2024-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0002_rename_course_student_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='contact',
        ),
    ]
